import { archiveDrop, saveDrop } from "@/features/admin/server/drop-actions";

import { Flash } from "./flash";

type Media = { id: string; originalName: string; storageKey: string };
type Customization = { id: string; label: string; type: "NAME" | "NUMBER" };
type Product = { id: string; name: string; status: string; customizations: Customization[]; bundleComponents: Array<{ id: string; label: string; componentProduct: { name: string; customizations: Customization[] } }> };
type DropValue = { id: string; title: string; slug: string | null; shortText: string; startsAt: Date | null; endsAt: Date | null; status: "DRAFT" | "PUBLISHED" | "ARCHIVED"; isPrimary: boolean; heroMediaId: string | null; heroAlt: string | null; dropProducts: Array<{ productId: string; priceCents: number; compareAtPriceCents: number | null; isVisible: boolean; marketingMediaId: string | null; customizationPrices: Array<{ productCustomizationId: string; bundleComponentId: string | null; isEnabled: boolean; surchargeCents: number }> }> };

function localDate(value: Date | null | undefined) { if (!value) return ""; const offset = value.getTimezoneOffset() * 60_000; return new Date(value.valueOf() - offset).toISOString().slice(0, 16); }
function euros(cents: number | null | undefined) { return cents == null ? "" : (cents / 100).toFixed(2); }

export function DropForm({ drop, products, media, searchParams }: { drop?: DropValue; products: Product[]; media: Media[]; searchParams?: { ok?: string; error?: string } }) {
  const selected = new Map(drop?.dropProducts.map((item) => [item.productId, item])); const field = "mt-1 w-full rounded border border-slate-300 bg-white px-3 py-2";
  return <div className="space-y-5"><Flash searchParams={searchParams} /><form action={saveDrop} className="space-y-6">{drop ? <input name="id" type="hidden" value={drop.id} /> : null}
    <section className="grid gap-4 rounded-xl bg-white p-6 shadow-sm md:grid-cols-2"><h2 className="text-xl font-bold md:col-span-2">Información y publicación</h2>
      <label className="text-sm font-semibold">Título<input className={field} defaultValue={drop?.title} maxLength={191} name="title" required /></label><label className="text-sm font-semibold">Slug<input className={field} defaultValue={drop?.slug ?? ""} maxLength={191} name="slug" placeholder="Se genera desde el título" /></label>
      <label className="text-sm font-semibold md:col-span-2">Texto corto<textarea className={field} defaultValue={drop?.shortText} name="shortText" required rows={3} /></label>
      <label className="text-sm font-semibold">Inicio<input className={field} defaultValue={localDate(drop?.startsAt)} name="startsAt" type="datetime-local" /></label><label className="text-sm font-semibold">Fin<input className={field} defaultValue={localDate(drop?.endsAt)} name="endsAt" type="datetime-local" /></label>
      <label className="text-sm font-semibold">Estado<select className={field} defaultValue={drop?.status === "ARCHIVED" ? "DRAFT" : (drop?.status ?? "DRAFT")} name="status"><option value="DRAFT">Borrador</option><option value="PUBLISHED">Publicado</option></select></label><label className="flex items-end gap-2 pb-2 text-sm font-semibold"><input defaultChecked={drop?.isPrimary} name="isPrimary" type="checkbox" /> Drop principal</label>
      <label className="text-sm font-semibold">Hero<select className={field} defaultValue={drop?.heroMediaId ?? ""} name="heroMediaId"><option value="">Sin imagen</option>{media.map((asset) => <option key={asset.id} value={asset.id}>{asset.originalName}</option>)}</select></label><label className="text-sm font-semibold">Alt del hero<input className={field} defaultValue={drop?.heroAlt ?? ""} maxLength={255} name="heroAlt" /></label>
    </section>
    <section className="space-y-4 rounded-xl bg-white p-6 shadow-sm"><div><h2 className="text-xl font-bold">Productos, precios y suplementos</h2><p className="text-sm text-slate-500">Marca los productos incluidos. Los importes se introducen en euros.</p></div>
      {products.length === 0 ? <p className="rounded border border-dashed p-5 text-slate-600">Primero crea productos.</p> : products.map((product) => { const current = selected.get(product.id); const configs = [...product.customizations.map((custom) => ({ custom, componentId: null as string | null, context: "Producto" })), ...product.bundleComponents.flatMap((component) => component.componentProduct.customizations.map((custom) => ({ custom, componentId: component.id, context: `${component.label}: ${component.componentProduct.name}` })))]; return <fieldset className="rounded-lg border border-slate-200 p-4" key={product.id}>
        <label className="flex items-center gap-2 text-lg font-bold"><input defaultChecked={Boolean(current)} name="productIds" type="checkbox" value={product.id} />{product.name}<span className="text-xs font-normal text-slate-500">{product.status}</span></label>
        <div className="mt-3 grid gap-3 md:grid-cols-4"><label className="text-sm font-semibold">Precio (€)<input className={field} defaultValue={euros(current?.priceCents)} min="0.01" name={`price_${product.id}`} step="0.01" type="number" /></label><label className="text-sm font-semibold">Precio comparativo (€)<input className={field} defaultValue={euros(current?.compareAtPriceCents)} min="0" name={`compare_${product.id}`} step="0.01" type="number" /></label><label className="text-sm font-semibold">Imagen de campaña<select className={field} defaultValue={current?.marketingMediaId ?? ""} name={`marketing_${product.id}`}><option value="">Imagen del producto</option>{media.map((asset) => <option key={asset.id} value={asset.id}>{asset.originalName}</option>)}</select></label><label className="flex items-end gap-2 pb-2 text-sm font-semibold"><input defaultChecked={current?.isVisible ?? true} name={`visible_${product.id}`} type="checkbox" /> Visible</label></div>
        {configs.length ? <div className="mt-4 grid gap-2 md:grid-cols-2">{configs.map(({ custom, componentId, context }) => { const existing = current?.customizationPrices.find((item) => item.productCustomizationId === custom.id && item.bundleComponentId === componentId); const key = `${product.id}_${custom.id}_${componentId ?? "product"}`; return <div className="grid grid-cols-[1fr_8rem] items-end gap-3 rounded bg-slate-50 p-3" key={key}><label className="text-sm"><span className="font-semibold">{custom.label}</span><br /><span className="text-xs text-slate-500">{context}</span><span className="mt-2 flex gap-2"><input defaultChecked={existing?.isEnabled} name={`enabled_${key}`} type="checkbox" /> Habilitada</span></label><label className="text-xs font-semibold">Suplemento (€)<input className={field} defaultValue={euros(existing?.surchargeCents ?? 0)} min="0" name={`surcharge_${key}`} step="0.01" type="number" /></label></div>; })}</div> : null}
      </fieldset>; })}
    </section>
    <div className="flex gap-3"><button className="rounded bg-[var(--rr-navy-900)] px-6 py-3 font-bold text-white" type="submit">Guardar drop</button></div>
  </form>{drop && drop.status !== "ARCHIVED" ? <form action={archiveDrop}><input name="id" type="hidden" value={drop.id} /><button className="rounded border border-red-300 bg-white px-4 py-2 font-semibold text-red-700" type="submit">Archivar drop</button></form> : null}</div>;
}
